# Generated by Django 3.2.8 on 2021-10-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_content_comment_contentcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contentComment',
            new_name='content',
        ),
    ]
